# This is a basic workflow to help you get started with Actions

name: Create Archive

# Controls when the action will run. 
on:
    workflow_dispatch:
      inputs:
        name:
          description: "Name of the Release"
          required: true
        commit:
          decription: "Commit reference"
          required: false
          default: "master"
        tag:
          description: "Version tag"
          required: true
        prerelease:
          description: "Sets if prerelease or not"
          required: false
          default: "false"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          filename: 'calcpi.zip'
          exclusions: '*.git* /*node_modules/* .editorconfig nilakantha_method.py'
          
      - run: echo "$({ github.event.inputs.tag })"
      
      - name: Upload Release
        uses: ncipollo/release-action@v1
        with:
            artifacts: "calcpi.zip"
            name: "${{ github.event.inputs.name }}"
            commit: "${{ github.event.inputs.commit }}"
            tag: "${{ github.event.inputs.tag }}"
            prerelease: "${{ github.event.inputs.prerelease }}"
            token: ${{ secrets.GITHUB_TOKEN }}
